schema_version: 7.0
type: producer
identifier: ndi
title: NDI Input
version: 1.0
creator: Maksym Veremeyenko
license: LGPLv2.1
language: en
tags:
  - Audio
  - Video
  - Network
description: Audio/Video over IP input using NewTek's NDI technology
parameters:
  - identifier: resource
    argument: yes
    type: string
    title: NDI Source name
    description: Name of the NDI Source to receive
    required: yes
    mutable: no

